
# Add Mitigations
M1013 = Mitigation("M1013")
M1015 = Mitigation("M1015")
M1016 = Mitigation("M1016")
M1017 = Mitigation("M1017")
M1018 = Mitigation("M1018")
M1019 = Mitigation("M1019")
M1020 = Mitigation("M1020")
M1021 = Mitigation("M1021")
M1022 = Mitigation("M1022")
M1024 = Mitigation("M1024")
M1025 = Mitigation("M1025")
M1026 = Mitigation("M1026")
M1027 = Mitigation("M1027")
M1028 = Mitigation("M1028")
M1029 = Mitigation("M1029")
M1030 = Mitigation("M1030")
M1031 = Mitigation("M1031")
M1032 = Mitigation("M1032")
M1033 = Mitigation("M1033")
M1034 = Mitigation("M1034")
M1035 = Mitigation("M1035")
M1036 = Mitigation("M1036")
M1037 = Mitigation("M1037")
M1038 = Mitigation("M1038")
M1039 = Mitigation("M1039")
M1040 = Mitigation("M1040")
M1041 = Mitigation("M1041")
M1042 = Mitigation("M1042")
M1043 = Mitigation("M1043")
M1044 = Mitigation("M1044")
M1045 = Mitigation("M1045")
M1046 = Mitigation("M1046")
M1047 = Mitigation("M1047")
M1048 = Mitigation("M1048")
M1049 = Mitigation("M1049")
M1050 = Mitigation("M1050")
M1051 = Mitigation("M1051")
M1052 = Mitigation("M1052")
M1053 = Mitigation("M1053")
M1054 = Mitigation("M1054")
M1055 = Mitigation("M1055")
M1056 = Mitigation("M1056")
M1057 = Mitigation("M1057")
M1013.hasID.append("M1013")
M1015.hasID.append("M1015")
M1016.hasID.append("M1016")
M1017.hasID.append("M1017")
M1018.hasID.append("M1018")
M1019.hasID.append("M1019")
M1020.hasID.append("M1020")
M1021.hasID.append("M1021")
M1022.hasID.append("M1022")
M1024.hasID.append("M1024")
M1025.hasID.append("M1025")
M1026.hasID.append("M1026")
M1027.hasID.append("M1027")
M1028.hasID.append("M1028")
M1029.hasID.append("M1029")
M1030.hasID.append("M1030")
M1031.hasID.append("M1031")
M1032.hasID.append("M1032")
M1033.hasID.append("M1033")
M1034.hasID.append("M1034")
M1035.hasID.append("M1035")
M1036.hasID.append("M1036")
M1037.hasID.append("M1037")
M1038.hasID.append("M1038")
M1039.hasID.append("M1039")
M1040.hasID.append("M1040")
M1041.hasID.append("M1041")
M1042.hasID.append("M1042")
M1043.hasID.append("M1043")
M1044.hasID.append("M1044")
M1045.hasID.append("M1045")
M1046.hasID.append("M1046")
M1047.hasID.append("M1047")
M1048.hasID.append("M1048")
M1049.hasID.append("M1049")
M1050.hasID.append("M1050")
M1051.hasID.append("M1051")
M1052.hasID.append("M1052")
M1053.hasID.append("M1053")
M1054.hasID.append("M1054")
M1055.hasID.append("M1055")
M1056.hasID.append("M1056")
M1057.hasID.append("M1057")
M1013.hasName.append("Application Developer Guidance")
M1015.hasName.append("Active Directory Configuration")
M1016.hasName.append("Vulnerability Scanning")
M1017.hasName.append("User Training")
M1018.hasName.append("User Account Management")
M1019.hasName.append("Threat Intelligence Program")
M1020.hasName.append("SSL/TLS Inspection")
M1021.hasName.append("Restrict Web-Based Content")
M1022.hasName.append("Restrict File and Directory Permissions")
M1024.hasName.append("Restrict Registry Permissions")
M1025.hasName.append("Privileged Process Integrity")
M1026.hasName.append("Privileged Account Management")
M1027.hasName.append("Password Policies")
M1028.hasName.append("Operating System Configuration")
M1029.hasName.append("Remote Data Storage")
M1030.hasName.append("Network Segmentation")
M1031.hasName.append("Network Intrusion Prevention")
M1032.hasName.append("Multi-factor Authentication")
M1033.hasName.append("Limit Software Installation")
M1034.hasName.append("Limit Hardware Installation")
M1035.hasName.append("Limit Access to Resource Over Network")
M1036.hasName.append("Account Use Policies")
M1037.hasName.append("Filter Network Traffic")
M1038.hasName.append("Execution Prevention")
M1039.hasName.append("Environment Variable Permissions")
M1040.hasName.append("Behavior Prevention on Endpoint")
M1041.hasName.append("Encrypt Sensitive Information")
M1042.hasName.append("Disable or Remove Feature or Program")
M1043.hasName.append("Credential Access Protection")
M1044.hasName.append("Restrict Library Loading")
M1045.hasName.append("Code Signing")
M1046.hasName.append("Boot Integrity")
M1047.hasName.append("Audit")
M1048.hasName.append("Application Isolation and Sandboxing")
M1049.hasName.append("Antivirus/Antimalware")
M1050.hasName.append("Exploit Protection")
M1051.hasName.append("Update Software")
M1052.hasName.append("User Account Control")
M1053.hasName.append("Data Backup")
M1054.hasName.append("Software Configuration")
M1055.hasName.append("Do Not Mitigate")
M1056.hasName.append("Pre-compromise")
M1057.hasName.append("Data Loss Prevention")
M1036.hasDescription.append("Configure features related to account use like login attempt lockouts, specific login times, etc.")
M1015.hasDescription.append("Configure Active Directory to prevent use of certain techniques; use SID Filtering, etc.")
M1049.hasDescription.append("Use signatures or heuristics to detect malicious software.")
M1013.hasDescription.append("This mitigation describes any guidance or training given to developers of applications to avoid introducing security weaknesses that an adversary may be able to take advantage of.")
M1048.hasDescription.append("Restrict execution of code to a virtual environment on or in transit to an endpoint system.")
M1047.hasDescription.append("Perform audits or scans of systems, permissions, insecure software, insecure configurations, etc. to identify potential weaknesses.")
M1040.hasDescription.append("Use capabilities to prevent suspicious behavior patterns from occurring on endpoint systems. This could include suspicious process, file, API call, etc. behavior.")
M1046.hasDescription.append("Use secure methods to boot a system and verify the integrity of the operating system and loading mechanisms.")
M1045.hasDescription.append("Enforce binary and application integrity with digital signature verification to prevent untrusted code from executing.")
M1043.hasDescription.append("Use capabilities to prevent successful credential access by adversaries; including blocking forms of credential dumping.")
M1053.hasDescription.append("Take and store data backups from end user systems and critical servers. Ensure backup and storage systems are hardened and kept separate from the corporate network to prevent compromise.")
M1057.hasDescription.append("Use a data loss prevention (DLP) strategy to categorize sensitive data, identify data formats indicative of personal identifiable information (PII), and restrict exfiltration of sensitive data.")
M1042.hasDescription.append("Remove or deny access to unnecessary and potentially vulnerable software to prevent abuse by adversaries.")
M1055.hasDescription.append("This category is to associate techniques that mitigation might increase risk of compromise and therefore mitigation is not recommended.")
M1041.hasDescription.append("Protect sensitive information with strong encryption.")
M1039.hasDescription.append("Prevent modification of environment variables by unauthorized users and groups.")
M1038.hasDescription.append("Block execution of code on a system through application control, and/or script blocking.")
M1050.hasDescription.append("Use capabilities to detect and block conditions that may lead to or be indicative of a software exploit occurring.")
M1037.hasDescription.append("Use network appliances to filter ingress or egress traffic and perform protocol-based filtering. Configure software on endpoints to filter network traffic.")
M1035.hasDescription.append("Prevent access to file shares, remote access to systems, unnecessary services. Mechanisms to limit access may include use of network concentrators, RDP gateways, etc.")
M1034.hasDescription.append("Block users or groups from installing or using unapproved hardware on systems, including USB devices.")
M1033.hasDescription.append("Block users or groups from installing unapproved software.")
M1032.hasDescription.append("Use two or more pieces of evidence to authenticate to a system; such as username and password in addition to a token from a physical smart card or token generator.")
M1031.hasDescription.append("Use intrusion detection signatures to block traffic at network boundaries.")
M1030.hasDescription.append("Architect sections of the network to isolate critical systems, functions, or resources. Use physical and logical segmentation to prevent access to potentially sensitive systems and information. Use a DMZ to contain any internet-facing services that should not be exposed from the internal network. Configure separate virtual private cloud (VPC) instances to isolate critical cloud systems.")
M1028.hasDescription.append("Make configuration changes related to the operating system or a common feature of the operating system that result in system hardening against techniques.")
M1027.hasDescription.append("Set and enforce secure password policies for accounts.")
M1056.hasDescription.append("This category is used for any applicable mitigation activities that apply to techniques occurring before an adversary gains Initial Access, such as Reconnaissance and Resource Development techniques.")
M1026.hasDescription.append("Manage the creation, modification, use, and permissions associated to privileged accounts, including SYSTEM and root.")
M1025.hasDescription.append("Protect processes with high privileges that can be used to interact with critical system components through use of protected process light, anti-process injection defenses, or other process integrity enforcement measures.")
M1029.hasDescription.append("Use remote security log and sensitive file storage where access can be controlled better to prevent exposure of intrusion detection log data or sensitive information.")
M1022.hasDescription.append("Restrict access by setting directory and file permissions that are not specific to users or privileged accounts.")
M1044.hasDescription.append("Prevent abuse of library loading mechanisms in the operating system and software to load untrusted code by configuring appropriate library loading mechanisms and investigating potential vulnerable software.")
M1024.hasDescription.append("Restrict the ability to modify certain hives or keys in the Windows Registry.")
M1021.hasDescription.append("Restrict use of certain websites, block downloads/attachments, block Javascript, restrict browser extensions, etc.")
M1054.hasDescription.append("Implement configuration changes to software (other than the operating system) to mitigate security risks associated to how the software operates.")
M1020.hasDescription.append("Break and inspect SSL/TLS sessions to look at encrypted web traffic for adversary activity.")
M1019.hasDescription.append("A threat intelligence program helps an organization generate their own threat intelligence information and track trends to inform defensive priorities to mitigate risk.")
M1051.hasDescription.append("Perform regular software updates to mitigate exploitation risk.")
M1052.hasDescription.append("Configure Windows User Account Control to mitigate risk of adversaries obtaining elevated process access.")
M1018.hasDescription.append("Manage the creation, modification, use, and permissions associated to user accounts.")
M1017.hasDescription.append("Train users to be aware of access or manipulation attempts by an adversary to reduce the risk of successful spearphishing, social engineering, and other techniques that involve user interaction.")
M1016.hasDescription.append("Vulnerability scanning is used to find potentially exploitable software vulnerabilities to remediate them.")